name: last_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  zoom_tap_animation: ^1.1.0
  flutter_barcode_scanner: ^2.0.0
  qr_code_scanner: ^1.0.1
  connectivity_plus: ^5.0.0
  equatable: ^2.0.5
  lottie: ^2.6.0
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/lottie/
    - assets/images/
